### ISSUE TITLE
Check cover image

### ISSUE THREAD

**Issue by dacacioa** [EDyO/appu#14]
If you define a incorrect image (format or path incorrect) it seems that the final export finish with an appu IOError.

We have to implement a check file exist check to this parameter.

**Comment by dacacioa** [comment]
Pending to confirm.

**Comment by dacacioa** [comment]
Confirmed.

**Comment by ifosch** [comment]
Apparently, this got fixed. Also the solution should be much broader as appu output is currently almost silent. This will be addressed in the future.
